### PR TITLE
Handle timezone information during DateTime parsing (#46)

### LINKED ISSUE #42: Fix TibiadataDatetimeV3 UTC timezone problem
Seems like the _TibiadataDatetimeV3_ doesn't take the time zone in to account when parsing content.
Tests are therefore failing when running locally, but work on GitHub.

### PR DESCRIPTION
**Pull request by tobiasehlert**
* Handle timezone information during DateTime parsing
* adjusting asserts to be UTC
* updating TibiadataDatetimeV3 with correct format

Fixes #42

### CODE REVIEW

File: src/TibiaDataUtils.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+	var (
+		returnDate time.Time
+		err        error
+	)
+
+	// If statement to determine if date string is filled or empty
+	if date == "" {
+		// The string that should be returned is the current timestamp in UTC
+		returnDate = time.Now().UTC()
```
Comment (kamilon) [inline src/TibiaDataUtils.go:23]: .UTC isn't needed here as it'll be done before the func returns

Comment (tobiasehlert) [reply src/TibiaDataUtils.go]: nice catch! fixed :)
